# Dependencies
markdown:         redcarpet
redcarpet:
    extensions:   ["tables"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            mwhittaker.io
tagline:          ""
url:              http://mwhittaker.github.io

author:
  name:           'Michael Whittaker'
  url:            http://github.com/mwhittaker/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/mwhittaker/
